language: ruby
rbenv:
- 2.4.1
services:
- postgresql
before_script:
- bundle exec rake db:{drop,create,migrate,seed}
env:
matrix:
  include:
  - secure: "TxejY8r5e0L2P7B6OeZ46hBPlOeS9IOxRbkN6R0/UhtMBgUKMv0L+K7C5/HsiGszXEfj6ccz/kMpqCTprQ6jh0uVKhj1zcFT8XMUn2fpMBu1vyqsQBRcaI3x28sJn2Uihim8zVsAh9ZiH1eGQWP/y8AEZUMuhnyKfuZjCIWbG6GRDoWveCk3o87nqKYdRyigr+xrgv9f71jcPaRujMNm1Lhm4dfRKwPBHM6DJVHL44b+9CPWbKteE9Qkz+AP3e0HmsBF7RrGuCM6cg6WfvOo2uBn/MPkw1oCViG9Zsh68MwjXSEtqbxzfy9RwkouQ/VLsgcKxvt7SFYa4vUQhu3F0wMxD0fiQ5fZYVIxiQKTz/32g2yioWLcfecxS4Ms7lpN9iuf4Exn5Qu7WRtR5CQ1Jh7/GB/Sh62WGEH7r2p57IMlbt71dazzwU5RS7iNhQC7aetRjuApOZU3GcTKQfgM4J4SZG8ZLJAwnW/psaZ1l1c/QMMcSAuuLYhRSD6NDQlNZ6qpBJKT9g9Te1KAHxAJfoUKPv94K5e9RXN4gCBnOiGkf4NoyFFnDoInIBc+9w/DC6VLF3fLNnBli7yHsPbubZat2l3SIL++eDj24nD5Yc8paWbHAOAGlHU6XEvhcrk6d2NJCaaODJ0+h+feBNsTQk/2Ws/3ZFlhNKBQQAHp10Q="
  - secure: "rTW5zaj9gOdTLXGvIIKb7q3040AUmYYxPCv3R5/IeY+YMnUdQSF1iFnmTz9eL0OiEFHMs4yPlZThLUVpk3foqTrAb7s15eaLEl/GFvabfMLbmgEHN33Duw1AdMIBpOdz1Uf/SOSZmOWrLdxEX2dFmTPzEH874OshHdIE/ecofyJUDaL4+Q1yKAoXHfEeruuFcEmZS1Jb/5hYWaKQc2URpIvxLQ/IORNGeCOOn9+sYqNXl+fJoJJbQTGDVcy9REkQvNWbVExuSTlAwCMPztR31eU6wIvCmXUq0x62yaK+wgU9grF39vseyqY2fbQwFtojk+y9Bb4x73OUB1dYP7h7XrA6U4rIZCNLenpoeYWbtTUbWBUm5gASJZi4codtlrw8g0PZOppO3DMoRd+nrALkYsx4AYCWGmgtApNlfGpFpjzbu8EowhoE2PpfgdEfs3XOyocS/pl68Ge5Mt1RMJxQ2pbixn4gj3wprF2SlJt2SVM5mhNaiempyM1aa1OpGgy/VHM9iWAjIiGzO7zIsMrXVIR2V1zHnfQAe8PPG8plt16lRwbdHuujwE7Y2NgntRPuz4a03xN1n9V7wiymF1JNCMCeTMYntYfBkOWToMcTZB059LKDLVqIdIoTagC3AJAj+0CSalr30SABtlCwSBbv3Ja0lRUxd2U9MeXxA2UXy8k="
